### ISSUE TITLE
fs.rmdir deprecated

### ISSUE THREAD

**Issue by chesucr** [feross/cross-zip#38]
I got this warning from your package. It looks easy to fix. Just to let you know:

```
(node:18676) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
    at emitRecursiveRmdirWarning (node:internal/fs/utils:869:13)
    at Object.rmdir (node:fs:1164:5)
    at doZip (C:\...\node_modules\cross-zip\index.js:49:10)
    at C:\...\node_modules\cross-zip\index.js:22:9
    at FSReqCallback.oncomplete (node:fs:198:5)
```

**Comment by sstoime** [comment]
Hello, I’m following up on this warning as it is still present. Is there any update on whether this can be addressed?

**Comment by Dadadah** [comment]
This now throws an error in node 25+
